// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utxinrvceloqhqeujanc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0eGlucnZjZWxvcWhxZXVqYW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTkzMzksImV4cCI6MjA2NTU3NTMzOX0.m9OI3UM_WIpfRNr7euxiVzmaV4lKjMcQkE7HhXRkJ-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);